### ISSUE TITLE
FreeBSD

### ISSUE THREAD

**Issue by Strykar** [jappeace/distrowatch1graph1svg#2]
Shouldn't FreeBSD start around 1993?

**Comment by jappeace** [comment]
Yes, according to wikipedia. The current version just scrapes all data from distrowatch.

I'm planning on adding another step to the pipeline to correct these errors.

**Comment by Strykar** [comment]
No, some of us used it that long ago.
And according to the FreeBSD project themselves - https://www.freebsd.org/doc/handbook/history.html
http://www.tldp.org/HOWTO/Secure-Programs-HOWTO/history.html
https://www.levenez.com/unix/unix_a4.pdf

Linux used a BSD TCP/IP stack until the lawsuits IIRC.

**Comment by jappeace** [comment]
... I'm not disagreeing. Anyway this script uses distrowatch as a datasource:

https://distrowatch.com/table.php?distribution=freebsd

The release table is used to determine when a distribution was "born". (I didn't consider that historical part which I just see now at the bottom of the page, maybe I should add parsing that too).

**Comment by jappeace** [comment]
FreeBSD now starts in 1993 as it should be in the [new version](https://upload.wikimedia.org/wikipedia/commons/1/15/Linux_landscape_2016_II_%28and_bsd%27s%29.png). It is corrected "manually" [here](https://github.com/jappeace/distrowatch1graph1svg/blob/master/correct.py#L88).
