### ISSUE TITLE
Banned on distrowatch

### ISSUE THREAD

**Issue by 0Karakurt0** [jappeace/distrowatch1graph1svg#3]
I tried to regenerate this image, due to age of old one? but in the middle of parsing I got error 101. Is there a way to avoid such a thing?

**Comment by jappeace** [comment]
Are you getting a http 101 error?

Google says it's because you're running http and they want you to run https: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/101#:~:text=The%20HTTP%20101%20Switching%20Protocols,the%20protocol%20it%20switched%20to.

Or are you getting a 101 error on windows, which indicates a corrupted file? Are you using windows?

Please also tell me how you're executing the command, just copy past the arguments you're running.

**Comment by 0Karakurt0** [comment]
Yes, error 101. I am running Arch Linux, and the commands I executed where simple:
`git clone $link ; cd di* ; python __main__.py`
No additional arguments.

So, is there a way  to specify protocol?
And what's strange about protocol idea, I had no problems accesing distrowatch, but after running skript I got error 101 on every device in my network

**Comment by 0Karakurt0** [comment]
I asked my friend what to do, they noticed that you missing a header. Check in commits

**Comment by 0Karakurt0** [comment]
*in pull requests

**Comment by jappeace** [comment]
Does that fix it for you then? Did you test it?

**Comment by jappeace** [comment]
> And what's strange about protocol idea, I had no problems accesing distrowatch, but after running skript I got error 101 on every device in my network

It's an argument: https://github.com/jappeace/distrowatch1graph1svg/blob/master/__main__.py#L43

The help talks about http, but the default is https. So if you didn't use that it maybe the header like you mention, I don't know.

**Comment by 0Karakurt0** [comment]
> Does that fix it for you then? Did you test it?

  I am still blocked, cant test it

**Comment by 0Karakurt0** [comment]
I found working VPN, I'll test in a couple minutes

**Comment by jappeace** [comment]
Did you get your pr to work then?

**Comment by 0Karakurt0** [comment]
No. feels like I have been blocked by some hardware-related key, because I can acces distrowatch through vpn on my phone, but when I share same VPN through usb-modem it does't work. Or maybe I am dumb and doing it wrong, idk, I'm not that expirienced yet.

**Comment by 0Karakurt0** [comment]
Okay, I'm free again and turns out that this header idea doesn't work. But slower internet connection through VPN worked, so now I have database to work with)
